# Generated by Django 2.2 on 2020-06-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='User',
            new_name='user',
        ),
    ]
